- name: setup loadbalance
  hosts: loadbalancer
  become: yes
  tasks:
    - name: remove old config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      
    - name: import config
      copy:
        src: ./loadbalance.conf.j2
        dest: /etc/nginx/conf.d/loadbalance.conf
      notify: restart-nginx
    
  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted